// GENERATED by @edgedb/generate v0.5.3

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
export type $EdgePostλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "content": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, true>;
  "title": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
}>;
type $EdgePost = $.ObjectType<"default::EdgePost", $EdgePostλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $EdgePost = $.makeType<$EdgePost>(_.spec, "b4da05c8-1a1f-11ef-9988-dd4b879f2b73", _.syntax.literal);

const EdgePost: $.$expr_PathNode<$.TypeSet<$EdgePost, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($EdgePost, $.Cardinality.Many), null);



export { $EdgePost, EdgePost };

type __defaultExports = {
  "EdgePost": typeof EdgePost
};
const __defaultExports: __defaultExports = {
  "EdgePost": EdgePost
};
export default __defaultExports;
